apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: emby-configured
  name: emby-configured
spec:
  output:
    to:
      kind: ImageStreamTag
      name: emby-configured:latest
  resources: {}
  source:
    contextDir: configured
    git:
      uri: https://github.com/deads2k/mediabrowser-server-docker
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: emby-base:latest
    type: Docker
  triggers:
  - github:
      secret: F2DrKO5Qh18YHLXGeMi6
    type: GitHub
  - generic:
      secret: F825qjppaFbaH5C5wg1A
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange