apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: emby-configured
  name: emby-configured
spec:
  replicas: 1
  selector:
    app: emby-configured
    deploymentconfig: emby-configured
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: emby-configured
        deploymentconfig: emby-configured
    spec:
      containers:
      - image: 172.30.201.81:5000/emby-configured/emby-configured@sha256:04aaea17a647df97d61bb0e99b14c0ebc445bc13f87ab1c8efdcb51863c147b6
        name: emby-configured
        ports:
        - containerPort: 1900
          protocol: UDP
        - containerPort: 7359
          protocol: UDP
        - containerPort: 8096
          protocol: TCP
        - containerPort: 8920
          protocol: TCP
        resources: {}
        securityContext:
          capabilities: {}
          privileged: true
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /config
          name: volume-j7529
        - mountPath: /content
          name: volume-sh992
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      serviceAccount: privileged
      serviceAccountName: privileged
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /storage/openshift/emby-configured/config
        name: volume-j7529
      - hostPath:
          path: /storage/openshift/emby-configured/content
        name: volume-sh992
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - emby-configured
      from:
        kind: ImageStreamTag
        name: emby-configured:latest
    type: ImageChange

